name = "github-contributions-worker"
main = "src/index.ts"
compatibility_date = "2025-07-29"

[vars]
ENVIRONMENT = "production"

[env.development]
vars = { ENVIRONMENT = "development" }

[env.staging]
vars = { ENVIRONMENT = "staging" }